### ISSUE TITLE
Unable to go get github.com/philippdrebes/goji

### ISSUE THREAD

**Issue by florianbaer** [philippdrebes/goji#2]
As your main.go file is in the path github.com/philippdrebes/goji/cmd/goji I am unable to to execute the command `go get github.com/philippdrebes/goji`

instead i have to call `go get github.com/philippdrebes/goji/cmd/goji`
Is this by intention?

**Comment by philippdrebes** [comment]
Fixed the project structure, so that `go get github.com/philippdrebes/goji` will work.
